export type HistoricalCategory =
  | 'Todas as Áreas'
  | 'Ciência & Tecnologia'
  | 'Artes & Literatura'
  | 'Líderes & Política'
  | 'Filosofia & Pensamento'
  | 'Pioneiros & Exploração';

export interface HistoricalFigure {
  id: string;
  name: string;
  category: 'Ciência & Tecnologia' | 'Artes & Literatura' | 'Líderes & Política' | 'Filosofia & Pensamento' | 'Pioneiros & Exploração';
  era: string;
  nationality: string;
  gender: 'Masculino' | 'Feminino';
  field: string;
  keyFacts: string;
  hints: [string, string, string];
  famousQuote: string;
  bio: string;
  badge: string;
  tags: string[];
}

export const HISTORICAL_FIGURES: HistoricalFigure[] = [
  {
    id: 'einstein',
    name: 'Albert Einstein',
    category: 'Ciência & Tecnologia',
    era: 'Século XIX - XX (1879 - 1955)',
    nationality: 'Alemão (naturalizado Suíço e Americano)',
    gender: 'Masculino',
    field: 'Física Teórica e Cosmologia',
    keyFacts: 'Formulou a Teoria da Relatividade Geral e Especial, equação E=mc², ganhou o Prêmio Nobel de Física em 1921 pelo efeito fotoelétrico.',
    hints: [
      'Viveu no final do século XIX e metade do século XX, tendo nascido na Europa e falecido nos Estados Unidos.',
      'Sua equação mais famosa revolucionou a compreensão da relação entre massa e energia em todo o universo.',
      'Sua icônica foto com a língua para fora e cabelos despenteados tornou-se o símbolo mundial do gênio científico.',
    ],
    famousQuote: 'A imaginação é mais importante que o conhecimento.',
    bio: 'Físico teórico amplamente reconhecido como um dos maiores cientistas de todos os tempos. Desenvolveu a teoria da relatividade geral e explicou o efeito fotoelétrico.',
    badge: '⚛️ E=mc²',
    tags: ['física', 'nobel', 'relatividade', 'alemanha', 'ciência'],
  },
  {
    id: 'marie_curie',
    name: 'Marie Curie',
    category: 'Ciência & Tecnologia',
    era: 'Século XIX - XX (1867 - 1934)',
    nationality: 'Polonesa (naturalizada Francesa)',
    gender: 'Feminino',
    field: 'Física e Química (Radioatividade)',
    keyFacts: 'Descobriu os elementos Polônio e Rádio; pioneira nos estudos da radioatividade; única pessoa na história a ganhar dois Prêmios Nobel em áreas científicas distintas (Física e Química).',
    hints: [
      'Foi uma pioneira científica no século XIX e XX nascida no Leste Europeu que trabalhou em Paris.',
      'Foi a primeira mulher a ganhar um Prêmio Nobel e a primeira pessoa a ser laureada duas vezes em ciências diferentes.',
      'Descobriu elementos químicos radioativos, um dos quais batizou em homenagem à sua terra natal.',
    ],
    famousQuote: 'Na vida, não há nada a temer, apenas a ser compreendido.',
    bio: 'Cientista polonesa radicada na França, conduziu pesquisas pioneiras sobre radioatividade, descobrindo o rádio e o polônio e revolucionando a medicina e a física moderna.',
    badge: '☢️ Radioatividade',
    tags: ['química', 'física', 'nobel', 'mulher', 'polônia', 'frança'],
  },
  {
    id: 'da_vinci',
    name: 'Leonardo da Vinci',
    category: 'Artes & Literatura',
    era: 'Século XV - XVI (1452 - 1519)',
    nationality: 'Italiano (Florença / Renascimento)',
    gender: 'Masculino',
    field: 'Polímata: Pintura, Anatomia, Engenharia e Escultura',
    keyFacts: 'Pintou a Mona Lisa e A Última Ceia; desenhou o Homem Vitruviano; projetou protótipos de helicópteros, paraquedas e tanques séculos antes de sua invenção.',
    hints: [
      'Foi o expoente máximo do Renascimento Cultural italiano entre os séculos XV e XVI.',
      'Além de pintar a obra de arte mais famosa exposta no Museu do Louvre, era fascinado por anatomia e máquinas voadoras.',
      'Pintou o sorriso mais enigmático da história da arte e a emblemática mesa de "A Última Ceia".',
    ],
    famousQuote: 'A simplicidade é a sofisticação máxima.',
    bio: 'Polímata florentino do Renascimento italiano que se destacou como pintor, escultor, arquiteto, botânico, anatomista e inventor, autor da Mona Lisa.',
    badge: '🎨 Homem Vitruviano',
    tags: ['renascimento', 'itália', 'pintura', 'mona lisa', 'invenção'],
  },
  {
    id: 'santos_dumont',
    name: 'Alberto Santos Dumont',
    category: 'Ciência & Tecnologia',
    era: 'Século XIX - XX (1873 - 1932)',
    nationality: 'Brasileiro (Minas Gerais / Paris)',
    gender: 'Masculino',
    field: 'Aeronáutica e Engenharia',
    keyFacts: 'Pai da Aviação; primeiro a realizar voo público autônomo com um aparelho mais pesado que o ar (14-Bis) no Campo de Bagatelle em Paris (1906); inventou dirigíveis e o ultraleve Demoiselle.',
    hints: [
      'Nasceu no Brasil no estado de Minas Gerais e realizou seus maiores feitos aeronáuticos nos céus de Paris.',
      'Voou contornando a Torre Eiffel com um dirigível em 1901 e construiu o famoso modelo "Demoiselle".',
      'Em outubro de 1906, decolou, voou e pousou com o lendário "14-Bis" perante uma multidão na França.',
    ],
    famousQuote: 'As invenções são, sobretudo, o resultado de um trabalho teimoso.',
    bio: 'Aeronauta e inventor brasileiro pioneiro da aviação mundial. Conquistou Paris com seus dirigíveis e protagonizou o primeiro voo homologado com um avião mais pesado que o ar.',
    badge: '✈️ 14-Bis',
    tags: ['aviação', 'brasil', 'paris', 'invenção', 'minas gerais'],
  },
  {
    id: 'cleopatra',
    name: 'Cleópatra VII',
    category: 'Líderes & Política',
    era: 'Antiguidade (69 a.C. - 30 a.C.)',
    nationality: 'Egípcia / Grega Ptolomaica',
    gender: 'Feminino',
    field: 'Governante, Diplomata e Estrategista',
    keyFacts: 'Última governante ativa do Reino Ptolemaico do Egito; poliglota fluente em mais de 7 línguas; estabeleceu alianças políticas e amorosas com Júlio César e Marco Antônio.',
    hints: [
      'Viveu no século I a.C. às margens do Rio Nilo, no Norte da África.',
      'Falava diversas línguas, governou uma das civilizações mais antigas do mundo e desafiou a expansão de Roma.',
      'Sua corte ficava em Alexandria e suas alianças com líderes romanos como Júlio César e Marco Antônio mudaram a história.',
    ],
    famousQuote: 'Eu não serei exibida no triunfo de ninguém.',
    bio: 'Última rainha da dinastia ptolomaica no Egito Antigo, famosa por sua inteligência política, diplomacia afiada e defesa de seu reino contra o domínio romano.',
    badge: '👑 Faraó do Nilo',
    tags: ['egito', 'antiguidade', 'roma', 'rainha', 'liderança'],
  },
  {
    id: 'shakespeare',
    name: 'William Shakespeare',
    category: 'Artes & Literatura',
    era: 'Século XVI - XVII (1564 - 1616)',
    nationality: 'Inglês',
    gender: 'Masculino',
    field: 'Dramaturgia e Poesia',
    keyFacts: 'Considerado o maior escritor do idioma inglês; autor de obras universais como Hamlet, Romeu e Julieta, Macbeth e Otelo; co-proprietário do Globe Theatre.',
    hints: [
      'Viveu na Inglaterra elisabetana entre os séculos XVI e XVII.',
      'É amplamente considerado o maior dramaturgo de todos os tempos, tendo escrito mais de 37 peças e 154 sonetos.',
      'Criou a tragédia de dois jovens amantes em Verona e a célebre pergunta "Ser ou não ser, eis a questão".',
    ],
    famousQuote: 'Ser ou não ser, eis a questão.',
    bio: 'Poeta, dramaturgo e ator inglês do período renascentista, autor das mais aclamadas tragédias e comédias da literatura mundial no famoso Globe Theatre.',
    badge: '📜 Globe Theatre',
    tags: ['literatura', 'teatro', 'inglaterra', 'hamlet', 'poesia'],
  },
  {
    id: 'newton',
    name: 'Isaac Newton',
    category: 'Ciência & Tecnologia',
    era: 'Século XVII - XVIII (1643 - 1727)',
    nationality: 'Inglês',
    gender: 'Masculino',
    field: 'Física, Matemática e Astronomia',
    keyFacts: 'Formulou a Lei da Gravitação Universal e as Três Leis do Movimento (Mecânica Clássica); desenvolveu o cálculo infinitesimal; construiu o telescópio refletor.',
    hints: [
      'Viveu na Inglaterra durante a Revolução Científica do século XVII e início do XVIII.',
      'Publicou a monumental obra "Philosophiae Naturalis Principia Mathematica".',
      'A lenda conta que uma maçã caindo de uma macieira inspirou sua dedução da Lei da Gravidade.',
    ],
    famousQuote: 'Se vi mais longe, foi por estar sobre ombros de gigantes.',
    bio: 'Matemático e físico britânico que assentou as bases da mecânica clássica com suas três leis e formulou a lei da gravitação universal que rege os corpos celestes.',
    badge: '🍎 Gravitação Universal',
    tags: ['física', 'matemática', 'inglaterra', 'gravidade', 'cálculo'],
  },
  {
    id: 'frida_kahlo',
    name: 'Frida Kahlo',
    category: 'Artes & Literatura',
    era: 'Século XX (1907 - 1954)',
    nationality: 'Mexicana',
    gender: 'Feminino',
    field: 'Pintura e Artes Visuais',
    keyFacts: 'Conhecida por seus autorretratos intensos explorando dor, identidade mexicana, gênero e corpo; casada com Diego Rivera; viveu na célebre Casa Azul em Coyoacán.',
    hints: [
      'Nasceu e viveu na América Latina durante a primeira metade do século XX.',
      'Superou um grave acidente de ônibus na juventude que marcou sua arte através de pinturas feitas deitada na cama.',
      'Suas obras trazem autorretratos vívidos com trajes típicos mexicanos, sobrancelhas marcantes e animais exóticos.',
    ],
    famousQuote: 'Pés, para que os quero, se tenho asas para voar?',
    bio: 'Pintora mexicana que usou a arte para canalizar dores físicas e emocionais, criando autorretratos revolucionários impregnados de folclore indígena e simbolismo.',
    badge: '🌺 Casa Azul',
    tags: ['pintura', 'méxico', 'arte', 'autorretrato', 'cultura'],
  },
  {
    id: 'gandhi',
    name: 'Mahatma Gandhi',
    category: 'Líderes & Política',
    era: 'Século XIX - XX (1869 - 1948)',
    nationality: 'Indiano',
    gender: 'Masculino',
    field: 'Ativismo, Política e Resistência Pacífica',
    keyFacts: 'Liderou o movimento de independência da Índia contra o Império Britânico usando a Não-Violência (Ahimsa) e a Desobediência Civil (Satyagraha); liderou a Marcha do Sal em 1930.',
    hints: [
      'Atuou na Ásia e na África do Sul durante o final do século XIX e primeira metade do século XX.',
      'Defendeu fervorosamente que a mudança política deve ser feita sem o uso de armas ou agressão física.',
      'Liderou a histórica "Marcha do Sal" e usava roupas simples de algodão que ele mesmo fiava.',
    ],
    famousQuote: 'Seja a mudança que você quer ver no mundo.',
    bio: 'Advogado e líder espiritual da Índia que conduziu o país à independência através da filosofia da não-violência e inspirou movimentos civis por liberdade em todo o planeta.',
    badge: '🕊️ Satyagraha',
    tags: ['paz', 'índia', 'não-violência', 'independência', 'líder'],
  },
  {
    id: 'alan_turing',
    name: 'Alan Turing',
    category: 'Ciência & Tecnologia',
    era: 'Século XX (1912 - 1954)',
    nationality: 'Britânico',
    gender: 'Masculino',
    field: 'Matemática, Lógica e Ciência da Computação',
    keyFacts: 'Pai da Ciência da Computação e da Inteligência Artificial; decifrou a máquina alemã Enigma em Bletchley Park na Segunda Guerra Mundial; criou a Máquina de Turing e o Teste de Turing.',
    hints: [
      'Foi um brilhante matemático britânico que viveu na primeira metade do século XX.',
      'Trabalhou secretamente em Bletchley Park decodificando mensagens cifradas vitais durante a Segunda Guerra Mundial.',
      'Concebeu o teste definitivo para determinar se uma máquina pode pensar de forma indistinguível de um ser humano.',
    ],
    famousQuote: 'Às vezes são as pessoas de quem ninguém espera nada que fazem as coisas que ninguém pode imaginar.',
    bio: 'Matemático e criptoanalista britânico fundamental para a vitória dos Aliados na Segunda Guerra e formulador dos conceitos teóricos que deram origem aos computadores modernos.',
    badge: '💻 Máquina de Turing',
    tags: ['computação', 'matemática', 'inteligência artificial', 'criptografia', 'reino unido'],
  },
  {
    id: 'joana_darc',
    name: 'Joana d\'Arc',
    category: 'Líderes & Política',
    era: 'Idade Média (1412 - 1431)',
    nationality: 'Francesa',
    gender: 'Feminino',
    field: 'Liderança Militar e Heroína Nacional',
    keyFacts: 'Camponesa que liderou o exército francês durante a Guerra dos Cem Anos; libertou a cidade de Orléans e permitiu a coroação de Carlos VII; canonizada santa padroeira da França.',
    hints: [
      'Viveu no século XV durante o período medieval na Europa.',
      'Mesmo sendo uma jovem camponesa sem treinamento militar prévio, vestiu armadura e liderou tropas no campo de batalha.',
      'Conhecida como a "Donzela de Orléans", foi julgada injustamente em Rouen e queimada na fogueira com apenas 19 anos.',
    ],
    famousQuote: 'Não tenho medo; eu nasci para fazer isto.',
    bio: 'Jovem heroína francesa da Guerra dos Cem Anos que, guiada por visões místicas, comandou o exército real, virou o curso do conflito contra os ingleses e se tornou santa e mártir.',
    badge: '⚔️ Donzela de Orléans',
    tags: ['frança', 'medieval', 'militar', 'heroína', 'orléans'],
  },
  {
    id: 'beethoven',
    name: 'Ludwig van Beethoven',
    category: 'Artes & Literatura',
    era: 'Século XVIII - XIX (1770 - 1827)',
    nationality: 'Alemão (Viena, Áustria)',
    gender: 'Masculino',
    field: 'Música Clássica e Composição',
    keyFacts: 'Fez a transição do Classicismo para o Romantismo; compôs 9 sinfonias monumentais; continuou compondo obras-primas mesmo após perder completamente a audição.',
    hints: [
      'Nasceu na Alemanha no final do século XVIII e consolidou sua brilhante carreira em Viena.',
      'Enfrentou uma tragédia pessoal devastadora para um músico: a perda progressiva da audição.',
      'Sua Nona Sinfonia termina com o eufórico "Hino à Alegria", obra que regeu sem conseguir ouvir uma única nota externa.',
    ],
    famousQuote: 'A música é uma revelação mais alta do que toda a sabedoria e filosofia.',
    bio: 'Compositor alemão que revolucionou a história da música ocidental, compondo sinfonias, concertos e sonatas para piano que expressavam paixões humanas épicas.',
    badge: '🎼 9ª Sinfonia',
    tags: ['música', 'alemanha', 'clássico', 'sinfonia', 'viena'],
  },
  {
    id: 'machado_de_assis',
    name: 'Machado de Assis',
    category: 'Artes & Literatura',
    era: 'Século XIX - XX (1839 - 1908)',
    nationality: 'Brasileiro (Rio de Janeiro)',
    gender: 'Masculino',
    field: 'Literatura, Conto e Crônica',
    keyFacts: 'Fundador e primeiro presidente da Academia Brasileira de Letras; inaugurou o Realismo no Brasil com Memórias Póstumas de Brás Cubas; autor de Dom Casmurro e Quincas Borba.',
    hints: [
      'Nasceu no Rio de Janeiro, filho de agregados no Morro do Livramento, e ascendeu ao topo da cultura nacional.',
      'Fundou a Academia Brasileira de Letras e ocupou perpétua presidência com a alcunha de "Bruxo do Cosme Velho".',
      'Escreveu um livro narrado por um defunto e eternizou o enigma dos olhos de ressaca de Capitu.',
    ],
    famousQuote: 'O tempo é um rato roedor das coisas.',
    bio: 'Considerado o maior escritor da literatura brasileira, mestre da ironia fina e do realismo psicológico, que criou personagens imortais como Brás Cubas e Capitu.',
    badge: '📖 Bruxo do Cosme Velho',
    tags: ['literatura', 'brasil', 'rio de janeiro', 'capitu', 'abl'],
  },
  {
    id: 'mandela',
    name: 'Nelson Mandela',
    category: 'Líderes & Política',
    era: 'Século XX - XXI (1918 - 2013)',
    nationality: 'Sul-Africano',
    gender: 'Masculino',
    field: 'Ativismo pelos Direitos Humanos e Presidência',
    keyFacts: 'Líder da luta contra o regime racista do Apartheid; ficou preso por 27 anos na Ilha Robben; primeiro presidente negro eleito democraticamente na África do Sul; Nobel da Paz em 1993.',
    hints: [
      'Nasceu no continente africano e dedicou toda a sua vida ao combate contra a segregação racial legalizada.',
      'Passou quase três décadas encarcerado em uma cela minúscula por lutar por direitos civis iguais.',
      'Conhecido carinhosamente como "Madiba", presidiu sua nação e promoveu a reconciliação através do esporte na Copa de Rugby de 1995.',
    ],
    famousQuote: 'A educação é a arma mais poderosa que você pode usar para mudar o mundo.',
    bio: 'Líder antiapartheid sul-africano que passou 27 anos na prisão antes de se tornar o primeiro presidente negro do país, símbolo planetário de conciliação e dignidade humana.',
    badge: '🇿🇦 Madiba',
    tags: ['áfrica do sul', 'apartheid', 'direitos humanos', 'nobel', 'paz'],
  },
  {
    id: 'galileo',
    name: 'Galileu Galilei',
    category: 'Ciência & Tecnologia',
    era: 'Século XVI - XVII (1564 - 1642)',
    nationality: 'Italiano (Pisa / Florença)',
    gender: 'Masculino',
    field: 'Astronomia, Física e Método Científico',
    keyFacts: 'Aperfeiçoou o telescópio astronômico; descobriu as luas de Júpiter e crateras da Lua; defendeu o modelo Heliocêntrico de Copérnico; condenado pela Inquisição.',
    hints: [
      'Foi um astrônomo e físico italiano que viveu nos séculos XVI e XVII.',
      'Apontou uma luneta para o céu noturno e descobriu que Júpiter possuía luas próprias orbitando-o.',
      'Enfrentou o tribunal da Inquisição por afirmar que a Terra gira em torno do Sol, sussurrando a famosa frase: "E pur si muove" (E, no entanto, ela se move).',
    ],
    famousQuote: 'A matemática é o alfabeto com o qual Deus escreveu o universo.',
    bio: 'Pai da ciência moderna e da astronomia observacional, confirmou a teoria heliocêntrica ao observar as fases de Vênus e os satélites de Júpiter com seu telescópio.',
    badge: '🔭 E Pur Si Muove',
    tags: ['astronomia', 'itália', 'heliocentrismo', 'física', 'telescópio'],
  },
  {
    id: 'ada_lovelace',
    name: 'Ada Lovelace',
    category: 'Ciência & Tecnologia',
    era: 'Século XIX (1815 - 1852)',
    nationality: 'Britânica (Inglaterra)',
    gender: 'Feminino',
    field: 'Matemática e Pioneira da Computação',
    keyFacts: 'Escreveu o primeiro algoritmo da história projetado para ser executado por uma máquina (a Máquina Analítica de Charles Babbage); primeira programadora de computadores.',
    hints: [
      'Filha do célebre poeta Lord Byron, viveu na Inglaterra vitoriana do século XIX.',
      'Foi uma brilhante matemática que vislumbrou que máquinas poderiam manipular não apenas números, mas símbolos e música.',
      'Criou o primeiro algoritmo destinado a uma máquina de computação, tornando-se a primeira programadora da história.',
    ],
    famousQuote: 'A máquina analítica tece padrões algébricos assim como o tear de Jacquard tece flores e folhas.',
    bio: 'Matemática e escritora inglesa, pioneira da ciência da computação ao escrever as notas que continham o primeiro algoritmo computacional do mundo.',
    badge: '💻 1ª Programadora',
    tags: ['computação', 'matemática', 'algoritmo', 'inglaterra', 'mulher'],
  },
  {
    id: 'socrates',
    name: 'Sócrates',
    category: 'Filosofia & Pensamento',
    era: 'Antiguidade Clássica (470 a.C. - 399 a.C.)',
    nationality: 'Grego (Atenas)',
    gender: 'Masculino',
    field: 'Filosofia Ocidental e Ética',
    keyFacts: 'Pai da Filosofia Ocidental; desenvolveu o Método Socrático (Maiêutica e ironia); nunca escreveu um livro (seus pensamentos foram registrados por Platão); condenado a beber cicuta.',
    hints: [
      'Caminhava pelas praças e mercados da Atenas antiga no século V a.C. fazendo perguntas desconcertantes aos cidadãos.',
      'Não deixou nenhuma obra escrita; seus diálogos filosóficos chegaram até nós através de seu discípulo Platão.',
      'Ficou imortalizado pela máxima "Só sei que nada sei" e preferiu beber o veneno cicuta a renunciar à verdade.',
    ],
    famousQuote: 'Só sei que nada sei.',
    bio: 'Filósofo ateniense que fundou a tradição filosófica ocidental, desafiando certezas através de perguntas perspicazes e ensinando a buscar a virtude e o autoconhecimento.',
    badge: '🏛️ Método Socrático',
    tags: ['filosofia', 'grécia', 'atenas', 'platão', 'antiguidade'],
  },
  {
    id: 'charles_darwin',
    name: 'Charles Darwin',
    category: 'Ciência & Tecnologia',
    era: 'Século XIX (1809 - 1882)',
    nationality: 'Britânico (Inglaterra)',
    gender: 'Masculino',
    field: 'Biologia, Geologia e Naturalismo',
    keyFacts: 'Propôs a Teoria da Evolução biológica por meio da Seleção Natural; viajou 5 anos a bordo do HMS Beagle (incluindo as Ilhas Galápagos); publicou "A Origem das Espécies" em 1859.',
    hints: [
      'Foi um naturalista britânico que realizou uma viagem de 5 anos ao redor do mundo a bordo do navio HMS Beagle.',
      'Estudou os bicos dos tentilhões e as carapaças das tartarugas gigantes nas Ilhas Galápagos.',
      'Publicou em 1859 "A Origem das Espécies", fundamentando como todas as formas de vida evoluem por seleção natural.',
    ],
    famousQuote: 'Não é o mais forte que sobrevive, nem o mais inteligente, mas o que melhor se adapta às mudanças.',
    bio: 'Naturalista britânico que formulou a teoria da evolução por seleção natural, transformando radicalmente as ciências biológicas e a compreensão das origens da vida.',
    badge: '🐢 Origem das Espécies',
    tags: ['biologia', 'evolução', 'inglaterra', 'galápagos', 'natureza'],
  },
  {
    id: 'abraham_lincoln',
    name: 'Abraham Lincoln',
    category: 'Líderes & Política',
    era: 'Século XIX (1809 - 1865)',
    nationality: 'Norte-Americano (EUA)',
    gender: 'Masculino',
    field: 'Presidência e Advocacia',
    keyFacts: '16º Presidente dos Estados Unidos; liderou o país durante a Guerra Civil Americana; assinou a Proclamação de Emancipação que aboliu a escravidão; Discurso de Gettysburg.',
    hints: [
      'Presidiu os Estados Unidos durante o século XIX, no momento mais sangrento de sua história.',
      'Assinou a célebre Proclamação de Emancipação que libertou os escravizados e preservou a União.',
      'Usava uma cartola alta inconfundível, proferiu o Discurso de Gettysburg e foi assassinado no Teatro Ford.',
    ],
    famousQuote: 'O governo do povo, pelo povo e para o povo não desaparecerá da Terra.',
    bio: '16º presidente americano que preservou a união da nação durante a Guerra de Secessão e extinguiu a escravidão com coragem moral e liderança política inigualável.',
    badge: '🎩 Emancipação',
    tags: ['estados unidos', 'guerra civil', 'liberdade', 'presidente', 'história'],
  },
  {
    id: 'van_gogh',
    name: 'Vincent van Gogh',
    category: 'Artes & Literatura',
    era: 'Século XIX (1853 - 1890)',
    nationality: 'Holandês (Países Baixos / França)',
    gender: 'Masculino',
    field: 'Pintura Pós-Impressionista',
    keyFacts: 'Pintou obras-primas como "A Noite Estrelada", "Os Girassóis" e "Terraço do Café à Noite"; vendeu apenas um quadro em vida; trocou centenas de cartas com seu irmão Theo.',
    hints: [
      'Pintor nascido na Holanda que produziu a maior parte de suas telas mais luminosas no sul da França.',
      'Em vida, era praticamente desconhecido e vendeu apenas uma pintura, sendo sustentado pelo irmão Theo.',
      'Suas pinceladas espessas e vibrantes em espiral deram vida à mágica tela "A Noite Estrelada".',
    ],
    famousQuote: 'Eu sonho com a minha pintura e pinto o meu sonho.',
    bio: 'Pintor pós-impressionista holandês cujas cores expressivas e pinceladas dinâmicas exerceram enorme influência na arte do século XX, autor de A Noite Estrelada.',
    badge: '🌻 Noite Estrelada',
    tags: ['arte', 'pintura', 'holanda', 'frança', 'impressionismo'],
  },
  {
    id: 'amelia_earhart',
    name: 'Amelia Earhart',
    category: 'Pioneiros & Exploração',
    era: 'Século XX (1897 - 1937)',
    nationality: 'Norte-Americana',
    gender: 'Feminino',
    field: 'Aviação e Exploração Aérea',
    keyFacts: 'Primeira mulher a cruzar o Oceano Atlântico em voo solo (1932); defensora incansável dos direitos femininos; desapareceu misteriosamente sobre o Pacífico ao tentar circunavegar o globo.',
    hints: [
      'Foi uma audaciosa aviadora pioneira durante as décadas de 1920 e 1930.',
      'Tornou-se a primeira mulher a voar sozinha sem escalas através do Oceano Atlântico.',
      'Seu avião desapareceu sem deixar vestígios em 1937 próximo à Ilha Howland durante uma tentativa de circum-navegação da Terra.',
    ],
    famousQuote: 'A maneira mais eficaz de fazer algo é fazê-lo.',
    bio: 'Pioneira da aviação norte-americana, quebrou recordes de altitude e velocidade e inspirou gerações de mulheres a ingressar na aviação e na ciência.',
    badge: '🛩️ Voo Solo Atlântico',
    tags: ['aviação', 'pioneira', 'atlântico', 'mulher', 'exploração'],
  },
  {
    id: 'neil_armstrong',
    name: 'Neil Armstrong',
    category: 'Pioneiros & Exploração',
    era: 'Século XX - XXI (1930 - 2012)',
    nationality: 'Norte-Americano (EUA)',
    gender: 'Masculino',
    field: 'Aeroespacial, Astronauta e Engenheiro',
    keyFacts: 'Comandante da missão Apollo 11; primeiro ser humano a pisar na superfície da Lua em 20 de julho de 1969.',
    hints: [
      'Foi um piloto de testes e astronauta que participou da corrida espacial na década de 1960.',
      'Em julho de 1969, desceu de uma escada metálica e colocou a sola de sua bota em solo extraterrestre.',
      'Ao descer do Módulo Lunar Eagle, declarou: "Um pequeno passo para o homem, um salto gigantesco para a humanidade".',
    ],
    famousQuote: 'Um pequeno passo para o homem, um salto gigantesco para a humanidade.',
    bio: 'Astronauta e aviador naval norte-americano que entrou para a história como o primeiro homem a caminhar na Lua na célebre missão Apollo 11.',
    badge: '🌕 Apollo 11',
    tags: ['lua', 'espaço', 'apollo', 'astronauta', 'ciência'],
  },
  {
    id: 'clarice_lispector',
    name: 'Clarice Lispector',
    category: 'Artes & Literatura',
    era: 'Século XX (1920 - 1977)',
    nationality: 'Brasileira (Nascida na Ucrânia / Rio de Janeiro)',
    gender: 'Feminino',
    field: 'Literatura, Romance e Contos Psicológicos',
    keyFacts: 'Uma das mais inovadoras escritoras em língua portuguesa; autora de "A Hora da Estrela", "Perto do Coração Selvagem" e "A Paixão Segundo G.H."; mestra do fluxo de consciência.',
    hints: [
      'Chegou ao Brasil ainda bebê com sua família vinda do Leste Europeu e radicou-se em Recife e no Rio de Janeiro.',
      'Revolucionou a prosa em língua portuguesa através de reflexões existenciais íntimas e epifanias silenciosas.',
      'Escreveu a pungente saga da retirante Macabéa em "A Hora da Estrela".',
    ],
    famousQuote: 'Renda-se, como eu me rendi. Mergulhe no que você não conhece como eu mergulhei.',
    bio: 'Romancista e contista modernista que explorou as profundezas da mente humana com linguagem visceral e poética, um dos maiores nomes da literatura mundial.',
    badge: '⭐ A Hora da Estrela',
    tags: ['literatura', 'brasil', 'modernismo', 'conto', 'escritora'],
  },
  {
    id: 'dom_pedro_ii',
    name: 'Dom Pedro II',
    category: 'Líderes & Política',
    era: 'Século XIX (1825 - 1891)',
    nationality: 'Brasileiro (Império do Brasil)',
    gender: 'Masculino',
    field: 'Imperador do Brasil, Mecenas e Cientista Amador',
    keyFacts: 'Segundo e último monarca do Império do Brasil; governou por quase 50 anos (1840-1889); amigo de Pasteur, Victor Hugo e Graham Bell; incentivador da ciência, imprensa e educação.',
    hints: [
      'Assumiu o comando do governo de uma grande nação sul-americana ainda jovem no chamado Golpe da Maioridade.',
      'Com sua longa barba branca, preferia passar noites observando estrelas pelo telescópio e conversando com cientistas.',
      'Foi o último imperador do Brasil, tendo governado por quase meio século até a proclamação da República.',
    ],
    famousQuote: 'Se eu não fosse imperador, desejaria ser professor.',
    bio: 'Segundo monarca do Império do Brasil, governou o país durante quase cinco décadas de estabilidade política, abolição progressiva e grande incentivo às artes e ciências.',
    badge: '👑 O Magnânimo',
    tags: ['brasil', 'império', 'monarquia', 'ciência', 'século xix'],
  },
  {
    id: 'alexandre_o_grande',
    name: 'Alexandre, o Grande',
    category: 'Líderes & Política',
    era: 'Antiguidade (356 a.C. - 323 a.C.)',
    nationality: 'Macedônio / Grego',
    gender: 'Masculino',
    field: 'Estrategista Militar, Rei e Conquistador',
    keyFacts: 'Rei da Macedônia e pupilo do filósofo Aristóteles; invicto em batalhas; conquistou o Império Persa e expandiu seu império da Grécia até o noroeste da Índia; fundou Alexandria.',
    hints: [
      'Foi um jovem rei guerreiro da Antiguidade educado pelo grande filósofo Aristóteles.',
      'Seu cavalo lendário chamava-se Bucéfalo e ele desatou o famoso "Nó Górdio" com um golpe de espada.',
      'Criou um dos maiores impérios da história antes dos 30 anos, estendendo seus domínios da Macedônia até o Rio Indo.',
    ],
    famousQuote: 'Não há nada impossível para aquele que tentar.',
    bio: 'Rei da Macedônia que construiu um império sem precedentes unindo o Ocidente e o Oriente, difundindo a cultura helenística pelas terras conquistadas.',
    badge: '⚔️ Conquistador do Mundo',
    tags: ['macedônia', 'grécia', 'antiguidade', 'conquista', 'império'],
  },
  {
    id: 'descartes',
    name: 'René Descartes',
    category: 'Filosofia & Pensamento',
    era: 'Século XVII (1596 - 1650)',
    nationality: 'Francês',
    gender: 'Masculino',
    field: 'Filosofia, Matemática e Racionalismo',
    keyFacts: 'Pai da Filosofia Moderna; criador do plano cartesiano que uniu a álgebra à geometria; formulou o método da dúvida hiperbólica com a célebre frase "Cogito, ergo sum".',
    hints: [
      'Viveu no século XVII na França e na Holanda, revolucionando tanto a filosofia quanto a matemática.',
      'Criou o sistema de coordenadas de eixos X e Y que todos aprendem na escola (plano que leva seu nome).',
      'Propôs duvidar de tudo até encontrar uma certeza irrefutável, resumida em: "Penso, logo existo".',
    ],
    famousQuote: 'Penso, logo existo (Cogito, ergo sum).',
    bio: 'Filósofo e matemático francês que inaugurou o racionalismo moderno e estabeleceu as coordenadas cartesianas na geometria analítica.',
    badge: '📐 Plano Cartesiano',
    tags: ['filosofia', 'matemática', 'frança', 'racionalismo', 'cartesiano'],
  },
  {
    id: 'mozart',
    name: 'Wolfgang Amadeus Mozart',
    category: 'Artes & Literatura',
    era: 'Século XVIII (1756 - 1791)',
    nationality: 'Austríaco (Salzburgo / Viena)',
    gender: 'Masculino',
    field: 'Composição Clássica e Piano',
    keyFacts: 'Criança prodígio que começou a compor aos 5 anos; compôs mais de 600 obras musicais (óperas como A Flauta Mágica e Don Giovanni, sinfonias e o famoso Réquiem incompleto).',
    hints: [
      'Nasceu em Salzburgo, na Áustria, no século XVIII, e viajou pela Europa exibindo seu talento musical extraordinário ainda na infância.',
      'Compôs mais de 600 obras-primas, incluindo óperas marcantes como "A Flauta Mágica".',
      'Morreu precocemente aos 35 anos em Viena enquanto compunha seu enigmático e dramático "Réquiem".',
    ],
    famousQuote: 'A música não está nas notas, mas no silêncio entre elas.',
    bio: 'Compositor austríaco considerado um dos maiores gênios musicais de todos os tempos, dono de uma inventividade melódica impecável do período clássico.',
    badge: '🎹 A Flauta Mágica',
    tags: ['música', 'áustria', 'prodígio', 'ópera', 'clássico'],
  },
  {
    id: 'stephen_hawking',
    name: 'Stephen Hawking',
    category: 'Ciência & Tecnologia',
    era: 'Século XX - XXI (1942 - 2018)',
    nationality: 'Britânico (Inglaterra)',
    gender: 'Masculino',
    field: 'Física Teórica e Cosmologia',
    keyFacts: 'Descobriu a Radiação Hawking emitida por buracos negros; autor do best-seller "Uma Breve História do Tempo"; superou a ELA (Esclerose Lateral Amiotrófica) por décadas usando sintetizador de voz.',
    hints: [
      'Foi um renomado físico e cosmólogo britânico em Cambridge que viveu até 2018.',
      'Superou um diagnóstico precoce de ELA e comunicava suas teorias brilhantes através de uma cadeira de rodas com sintetizador de voz.',
      'Dedicou sua vida ao estudo dos buracos negros e escreveu o clássico "Uma Breve História do Tempo".',
    ],
    famousQuote: 'Olhe para as estrelas e não para os seus pés.',
    bio: 'Físico teórico britânico que desvendou segredos dos buracos negros e da origem do cosmos, inspirando milhões como divulgador científico de alcance universal.',
    badge: '🕳️ Buracos Negros',
    tags: ['física', 'cosmologia', 'universo', 'tempo', 'inglaterra'],
  },
  {
    id: 'louis_pasteur',
    name: 'Louis Pasteur',
    category: 'Ciência & Tecnologia',
    era: 'Século XIX (1822 - 1895)',
    nationality: 'Francês',
    gender: 'Masculino',
    field: 'Microbiologia e Química',
    keyFacts: 'Pai da Microbiologia; derrubou a teoria da geração espontânea; inventou a pasteurização para conservação de alimentos; criou as vacinas contra o antraz e a raiva.',
    hints: [
      'Foi um químico e microbiologista francês do século XIX.',
      'Seu método de aquecimento e resfriamento rápido para matar bactérias em leites e bebidas leva seu próprio sobrenome.',
      'Desenvolveu a pioneira vacina contra a raiva (hidrofobia), salvando a vida de um menino mordido por um cão raivoso.',
    ],
    famousQuote: 'O acaso só favorece a mente preparada.',
    bio: 'Cientista francês pioneiro da microbiologia moderna que salvou incontáveis vidas com suas descobertas sobre germes, a técnica de pasteurização e vacinas essenciais.',
    badge: '🧪 Pasteurização',
    tags: ['microbiologia', 'vacina', 'frança', 'medicina', 'química'],
  },
];
